services:
  - type: web
    name: trending-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
